name: Build and test React Application 

on: 
  push:
    branches: [master]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20.x, 21.x]
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{matrix.node_version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node_version}}
    - name : npm ci, build and test 
      run : |
        npm ci 
        npm run build --if-present
        npm test 
